/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package teste

import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.routing.*
import io.ktor.http.*
import io.ktor.http.content.*
import io.ktor.application.*
import io.ktor.response.*
import io.ktor.features.*
import io.ktor.html.*
import io.ktor.request.*
import java.io.*
import kotlin.io.*
import java.time.LocalTime

fun transforma(lista:List<String>):List<String>{
 
    val maxLinha = 70
    if(lista.size>1){
        if(lista.get(0).length + lista.get(1).length < maxLinha){
    		return transforma ( listOf( lista.get(0) +" " + lista.get(1) ) + lista.drop(2) )
        }else{
            if(lista.get(0).length<maxLinha){           
          	  return listOf(lista.get(0)) + transforma(lista.drop(1))
      	  	}else{
              return listOf(lista.get(0).substring(0,maxLinha)) + transforma( listOf(lista.get(0).substring(maxLinha,lista.get(0).length)) + lista.drop(1))
            }
        }
    }else{
        if(lista.get(0).length<maxLinha){
          	  return lista
      	  	}else{
              return listOf(lista.get(0).substring(0,maxLinha)) + transforma( listOf(lista.get(0).substring(maxLinha,lista.get(0).length)))
            }
        return lista
    }
    
}


fun main() {

    embeddedServer(Netty, port = 7654){
        routing{

                get("/"){
            
                call.respondText("""
                
                <html>
                <head>
                    <title>Campo Minado</title> 
                </head>

                <form method="POST" action="chat" target="_blank">
                <input type="submit" value="Abrir sala de bate-papo"> 
                </form>

                </html> 
          
                """,ContentType.Text.Html)
            }
            post("/chat") {

                val hora =LocalTime.now().plusHours(-3)

                val parameters = call.receiveParameters() 
                val nome = 
                if(parameters["nome"] == null || parameters["nome"] == ""){
                    "Anônimo"
                }else{
                    parameters["nome"]
                }
                
                if( parameters["texto"] != null && parameters["texto"] != ""){
                     File("dados.txt").writeText( File("dados.txt").readText()+ ("("+hora.toString().substring(0,8)+
                     ") <b>"+nome +":</b> "+ parameters["texto"]+"\n") )
                }

                val conversaSize = File("dados.txt").readText().split("\n").size

                val mensagens =                
                if(conversaSize>=35){
                    File("dados.txt").readText().split("\n").drop(conversaSize-35)
                }else{
                    File("dados.txt").readText().split("\n")
                }
                
                File("dados.txt").writeText(mensagens.joinToString(separator="\n"))

                call.respondText("""

                <p style="font-family:monospace">

                ${ mensagens.map{x -> transforma(x.split(" ")).joinToString(separator="<br>")}.joinToString(separator="<br>") }
                <html>

                <head>
                    <title>Sala de bate-papo</title> 
                </head>

                <form method="POST" action="chat">
                <input type="text" size="15" maxlength="15" placeholder="Nome de Usuário" value="${nome}" name="nome">
                <input type="text" size="50" maxlength="100" placeholder="Insira seu texto" name="texto">
                <input type="submit" value="Enviar"> 
                </form>
                </p>
                </html>              
                """,ContentType.Text.Html)
            }
            static("/estatico/"){
                files("static/")
            }
        }
    }.start(wait=true)
}
